spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://14.225.205.235:5432/chat
    username: root
    password: P@ssword789
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://14.225.205.235:27017}
      username: root
      password: P@ssword789
      authentication-database: admin
      database: chat
  mail:
    host: smtp.gmail.com
    port: 587
  mvc:
    format:
      date-time: iso
      date: iso
      time: iso
server:
  port: 4160
logging:
  level:
    org:
      springframework:
        security: debug
        web:
          socket.config.WebSocketMessageBrokerStats: debug
    root: info
