spring:
  jpa:
    database:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://14.225.205.235:27017}
      username: root
      password: P@ssword789
      authentication-database: admin
      database: chat
  mail:
    host: smtp.gmail.com
    port: 587
  mvc:
    format:
      date-time: iso
      date: iso
      time: iso